name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Backend — Install / Lint / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm install
          npm run lint
          npm run test

      - name: Run build
        working-directory: ./backend
        run: npm run build

  frontend:
    name: Frontend — Install / Lint / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present

      - name: Run build
        working-directory: ./frontend
        run: npm run build

      