name: CI

on:
  pull_request:
    branches:
      - main
  
  push:
  workflow_dispatch:

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./backend/package.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Tests
        working-directory: ./backend
        run : npm run test
      - name: Run Lint
        working-directory: ./backend
        run: npm run lint
      - name: Run build
        working-directory: ./backend
        run: npm run build

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Tests
        working-directory: ./frontend
        run : npm run test
      - name: Run Lint
        working-directory: ./frontend
        run: npm run lint
      - name: Run build
        working-directory: ./frontend
        run: npm run build

      